### ISSUE TITLE
Rename to something that doesn't evoke "scurvy"

### ISSUE THREAD

**Issue by danmactough** [mcwhittemore/env-scry#4]
😉

**Comment by mcwhittemore** [comment]
Maybe I'm reading too much fantasy of late. :)

**Comment by mcwhittemore** [comment]
Logos?

![](http://cache2.asset-cache.net/gc/130853038-crystal-ball-displaying-recycling-symbol-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=tzmrSADDjEiKSt%2BhwMJJ%2FEZrtj1Z7kIeBmt2xdrWbHYTGVYNscPfsxjsiqQHUlaj2BbLtjWM61D%2Fx85G6YUl%2FA%3D%3D)

![](http://g01.a.alicdn.com/kf/HTB1Qpj2HVXXXXaWXVXXq6xXFXXXe/Free-Shipping-8-Pieces-Highlights-A-font-b-Climate-b-font-font-b-Change-b-font.jpg)

**Comment by danmactough** [comment]
The second one is terrifying. Are those nuclear cooling towers?

Not exactly the same but...

![image](https://cloud.githubusercontent.com/assets/357481/8948093/263b5430-3571-11e5-9ef0-5ba4907884a9.png)
